---
swagger: "2.0"
info:
  description: "This is the swager server for the inter-domain security server.  This software is developed\
    \ under EU H2020 [http://5gzorro.eu](5GZORRO) project."
  version: "1.0"
  title: "Inter-domain security establishment"
  #termsOfService: "http://swagger.io/terms/"
  contact:
    email: "josemaria.jorquera@um.es"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
#host: "petstore.swagger.io"
#basePath: "/v2"
tags:
- name: "Gateway"
  description: "Methods related with the Wireguard-based VPN management"
  externalDocs:
    description: "Find out more"
    url: "http://5gzorro.eu"
schemes:
- "https"
- "http"
paths:
  /get_configuration:
    get:
      tags:
      - "Gateway"
      summary: "Gets the configuration of the VPN server"
      description: "This method allows downloading configuration options from server"
      operationId: "getConfig"
      produces:
      - "application/json"
      #parameters:
      #- name: "ip_address_server"
      #  description: "It is an end-point where VPN server will be installed"
      #  required: true
      #  type: "string"
      #- name: "port_server"
      #  description: "Specific port where VPN server will be available"
      #  required: true
      #  type: "integer"
      responses:
        200:
          description: "Successful operation."
          schema:
            $ref: "#/definitions/VPNInfo" 
  /add_client:
    post:
      tags:
      - "Gateway"
      summary: "Add a new client to the server"
      description: "This method adds a new client to the wireguard configuration, returning its defined VPN IP"
      operationId: "addClient"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "client_public_key"
        description: "Public key of the client to be added, in Curve25519 format."
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation."
          schema:
            $ref: "#/definitions/client_accepted"
        400:
          description: "Invalid status value."
  /remove_client:
    post:
      tags:
      - "Gateway"
      summary: "Remove a client from the server"
      description: "This method removes an existing client from the wireguard configuration."
      operationId: "addClient"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "client_public_key"
        description: "Public key of the client to be removed, in Curve25519 format."
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation."
        400:
          description: "Invalid status value."
  /connect_to_VPN:
    post:
      tags:
      - "Gateway"
      summary: "Add a connection to a foreign gateway"
      description: "This method establishes a new client connection using DIDs as the authentication mechanism. It uses the add_client method as auxiliary operation."
      operationId: "connectToVPN"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "ip_address_server"
        description: "It is an address where VPN server is running"
        required: true
        type: "string"
      - name: "port_server"
        description: "Specific port where VPN server will be available"
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid status value"
  /disconnect_to_VPN:
    post:
      tags:
      - "Gateway"
      summary: "Delete a connection to a foreign gateway"
      description: "This method carries out the completion of the established safe tunnel"
      operationId: "disconnetVPN"
      produces:
      - "application/json"
      parameters:
      - name: "ip_address_server"
        description: "It is an address where VPN server is running"
        required: true
        type: "string"
      - name: "port_server"
        description: "Specific port where VPN server will be available"
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid status value"
      #security:
      #- petstore_auth:
        #- "write:pets"
        #- "read:pets"
definitions:
  VPNInfo:
    type: "object"
    properties:
      did:
        type: "string"
        format: "DID"
      public_key:
        type: "string"
      IP_range:
        type: "string"
  client_accepted:
    type: "object"
    properties:
      assigned_ip:
        type: "string"
      server_public_key:
        type: "string"
externalDocs:
  description: "Find out more about 5GZORRO"
  url: "http://5gzorro.eu"
